### ISSUE TITLE
Data/Import scripts.

### ISSUE THREAD

**Issue by MP70** [DAXGRID/open-ftth-overview#1]
Hi @jesper-dax,

I have been reading through a lot of this code as I have some similar systems that do a very similar job here in UK. I wondered if you had any sample Danish test data that is open/you are happy to share, so that I could import this and try out your project?

**Comment by jesper-dax** [comment]
Hi @MP70
Unfortunately, we don't have any serious grid data that is open. Telcos in Denmark are not happy to share such data. However, we can do a demo for you, if you're interested to see how far we are with the project? It's quite easy to create a little network to play with.

You should also know, that the solution is still under development, but the part that deals with route networks, conduits etc. is finished. This is also where the solution is strong compared to other solutions. We are currently working on the fibre and circuit part of the solution.

You are welcome to contact me by email: jesper@dax.dk

**Comment by MP70** [comment]
Hi @jesper-dax,

Thank you for the response. I can import some route data, that shouldn't be a problem.

Are you saying that for example, the open-ftth-chart repo is, 'ready' to the extent that it should 'just work'? I did try to get it running at the weekend and came across a number of issues, should I raise these in that repo?

 I'd certainly like to invest some time into getting a demo of it running on my own system to see where you are upto.

Really useful to know, I already have code that does all the fibre/circuit parts so it will be interesting to see how you approach that. Please don't hesitate to let me know if there's anything I can help with there.

All the best

**Comment by runeanielsen** [comment]
Hi @MP70,

Thanks for your interest in the project. 

The project is currently running at one of our customers, but it still requires some manual setup that is currently not documented. We have decided to wait with the full documentation since we are still in a development phase where things change. In the future we might write a full guide on how to setup it up, but currently we are very busy with working on the whole system to finish it on time.

// Rune
